name: CVD Risk Toolkit Enhancement

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  enhance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Make script executable
      run: chmod +x enhance-toolkit.sh
    
    - name: Run enhancement script
      run: ./enhance-toolkit.sh
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.js index.html
        git commit -m "Enhance CVD Risk Toolkit with QRISK3 improvements" || echo "No changes to commit"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
