name: Combine JavaScript Files

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  combine-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Combine JavaScript files
        run: |
          # Create directory for combined files
          mkdir -p combined
          
          # Combine JavaScript files in the correct order
          cat validation.js.txt calculations.js.txt medication.js*.txt ui.js.txt > combined/combined.js
          
          # Copy styles.css.txt to combined directory
          cp styles.css.txt combined/styles.css
          
          # Create index.html with corrected structure in combined directory
          sed -e '/<!-- NON-EXECUTABLE READ-ONLY/,/-->$/d' index.txt > combined/index.html
          
          # Fix potential issues
          # Add event handler for toggling manual non-HDL entry
          echo '
          // Add missing event handler for manual non-HDL toggle
          document.addEventListener("DOMContentLoaded", function() {
            const toggleManualNonHDL = document.getElementById("toggle-manual-non-hdl");
            if (toggleManualNonHDL) {
              toggleManualNonHDL.addEventListener("click", function() {
                const nonHDLInput = document.getElementById("med-non-hdl");
                if (nonHDLInput) {
                  nonHDLInput.disabled = !nonHDLInput.disabled;
                  this.textContent = nonHDLInput.disabled ? "Enter manually" : "Use auto-calculation";
                }
              });
            }
            
            // Add event handler for statin selection
            const statinSelect = document.getElementById("med-statin");
            if (statinSelect) {
              statinSelect.addEventListener("change", function() {
                const doseSelect = document.getElementById("med-statin-dose");
                if (doseSelect) {
                  doseSelect.disabled = this.value === "none";
                  doseSelect.innerHTML = "<option value=\"\" selected>Select dose</option>";
                  
                  if (this.value !== "none") {
                    const doses = {
                      atorvastatin: [
                        {value: "10", text: "10 mg", intensity: "moderate"},
                        {value: "20", text: "20 mg", intensity: "moderate"},
                        {value: "40", text: "40 mg", intensity: "high"},
                        {value: "80", text: "80 mg", intensity: "high"}
                      ],
                      rosuvastatin: [
                        {value: "5", text: "5 mg", intensity: "moderate"},
                        {value: "10", text: "10 mg", intensity: "moderate"},
                        {value: "20", text: "20 mg", intensity: "high"},
                        {value: "40", text: "40 mg", intensity: "high"}
                      ],
                      simvastatin: [
                        {value: "10", text: "10 mg", intensity: "low"},
                        {value: "20", text: "20 mg", intensity: "moderate"},
                        {value: "40", text: "40 mg", intensity: "moderate"}
                      ],
                      pravastatin: [
                        {value: "10", text: "10 mg", intensity: "low"},
                        {value: "20", text: "20 mg", intensity: "low"},
                        {value: "40", text: "40 mg", intensity: "moderate"},
                        {value: "80", text: "80 mg", intensity: "moderate"}
                      ],
                      lovastatin: [
                        {value: "10", text: "10 mg", intensity: "low"},
                        {value: "20", text: "20 mg", intensity: "low"},
                        {value: "40", text: "40 mg", intensity: "moderate"}
                      ],
                      fluvastatin: [
                        {value: "20", text: "20 mg", intensity: "low"},
                        {value: "40", text: "40 mg", intensity: "low"},
                        {value: "80", text: "80 mg", intensity: "moderate"}
                      ],
                      pitavastatin: [
                        {value: "1", text: "1 mg", intensity: "low"},
                        {value: "2", text: "2 mg", intensity: "moderate"},
                        {value: "4", text: "4 mg", intensity: "moderate"}
                      ]
                    };
                    
                    if (doses[this.value]) {
                      doses[this.value].forEach(dose => {
                        const option = document.createElement("option");
                        option.value = dose.value;
                        option.textContent = dose.text;
                        option.dataset.intensity = dose.intensity;
                        doseSelect.appendChild(option);
                      });
                    }
                  }
                }
              });
            }
            
            // Add event handler for statin intolerance selection
            const intoleranceSelect = document.getElementById("med-statin-intolerance");
            if (intoleranceSelect) {
              intoleranceSelect.addEventListener("change", function() {
                const typeSelect = document.getElementById("med-intolerance-type");
                if (typeSelect) {
                  typeSelect.disabled = this.value === "no";
                }
              });
            }
            
            // Add event handler for PCSK9 inhibitor checkbox
            const pcsk9Checkbox = document.getElementById("med-pcsk9");
            if (pcsk9Checkbox) {
              pcsk9Checkbox.addEventListener("change", function() {
                const pcsk9Details = document.getElementById("pcsk9-details");
                if (pcsk9Details) {
                  pcsk9Details.style.display = this.checked ? "block" : "none";
                }
              });
            }
            
            // Add event handler for PCSK9 inhibitor type selection
            const pcsk9TypeSelect = document.getElementById("med-pcsk9-type");
            if (pcsk9TypeSelect) {
              pcsk9TypeSelect.addEventListener("change", function() {
                const doseSelect = document.getElementById("med-pcsk9-dose");
                if (doseSelect) {
                  doseSelect.disabled = !this.value;
                  doseSelect.innerHTML = "<option value=\"\" selected>Select dose</option>";
                  
                  if (this.value) {
                    const doses = {
                      evolocumab: [
                        {value: "140", text: "140 mg every 2 weeks"},
                        {value: "420", text: "420 mg monthly"}
                      ],
                      alirocumab: [
                        {value: "75", text: "75 mg every 2 weeks"},
                        {value: "150", text: "150 mg every 2 weeks"},
                        {value: "300", text: "300 mg monthly"}
                      ],
                      inclisiran: [
                        {value: "284", text: "284 mg initially, at 3 months, then every 6 months"}
                      ]
                    };
                    
                    if (doses[this.value]) {
                      doses[this.value].forEach(dose => {
                        const option = document.createElement("option");
                        option.value = dose.value;
                        option.textContent = dose.text;
                        doseSelect.appendChild(option);
                      });
                    }
                  }
                }
              });
            }
            
            // Add prevention category change handler
            const preventionCategory = document.getElementById("prevention-category");
            if (preventionCategory) {
              preventionCategory.addEventListener("change", function() {
                const secondaryDetails = document.getElementById("secondary-details");
                if (secondaryDetails) {
                  secondaryDetails.disabled = this.value !== "secondary";
                }
              });
            }
          });
          ' >> combined/combined.js
          
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Combine JavaScript files and fix missing event handlers"
          body: |
            This PR combines all JavaScript files into a single file and adds the missing event handlers:
            
            - Added event handler for toggling manual non-HDL entry
            - Added event handler for statin selection to populate doses
            - Added event handler for statin intolerance selection
            - Added event handler for PCSK9 inhibitor checkbox and type selection
            - Added event handler for prevention category changes
            
            The combined files are in the `combined` directory.
          branch: combined-files
          commit-message: "Combine JavaScript files and fix missing event handlers"
