name: Combine Files

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # Explicitly grant write permissions

jobs:
  combine-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up workspace
        run: |
          mkdir -p combined
          echo "// Combined JavaScript file for CVD Risk Toolkit" > combined/combined.js
          echo "/* Combined CSS file for CVD Risk Toolkit */" > combined/styles.css
        
      - name: List all files
        run: |
          echo "Listing files in repository:"
          ls -la
        
      - name: Combine JavaScript files
        run: |
          # Validation.js
          if [ -f "validation.js.txt" ]; then
            echo "Adding validation.js.txt to combined JS"
            cat validation.js.txt >> combined/combined.js
            echo -e "\n\n" >> combined/combined.js
          fi
          
          # Calculations.js
          if [ -f "calculations.js.txt" ]; then
            echo "Adding calculations.js.txt to combined JS"
            cat calculations.js.txt >> combined/combined.js
            echo -e "\n\n" >> combined/combined.js
          fi
          
          # Medication.js (try different possible filenames)
          if [ -f "medication.js.txt" ]; then
            echo "Adding medication.js.txt to combined JS"
            cat medication.js.txt >> combined/combined.js
            echo -e "\n\n" >> combined/combined.js
          fi
          
          if [ -f "medication.js (Part 1).txt" ]; then
            echo "Adding medication.js (Part 1).txt to combined JS"
            cat "medication.js (Part 1).txt" >> combined/combined.js
            echo -e "\n\n" >> combined/combined.js
          fi
          
          # UI.js
          if [ -f "ui.js.txt" ]; then
            echo "Adding ui.js.txt to combined JS"
            cat ui.js.txt >> combined/combined.js
            echo -e "\n\n" >> combined/combined.js
          fi
      
      - name: Add missing event handlers
        run: |
          echo "Adding missing event handlers to combined JS"
          cat >> combined/combined.js << 'EOL'
          // Add missing event handlers
          document.addEventListener("DOMContentLoaded", function() {
            // Toggle manual non-HDL entry
            const toggleManualNonHDL = document.getElementById("toggle-manual-non-hdl");
            if (toggleManualNonHDL) {
              toggleManualNonHDL.addEventListener("click", function() {
                const nonHDLInput = document.getElementById("med-non-hdl");
                if (nonHDLInput) {
                  nonHDLInput.disabled = !nonHDLInput.disabled;
                  this.textContent = nonHDLInput.disabled ? "Enter manually" : "Use auto-calculation";
                }
              });
            }
            
            // Add statin selection handler
            const statinSelect = document.getElementById("med-statin");
            if (statinSelect) {
              statinSelect.addEventListener("change", function() {
                const doseSelect = document.getElementById("med-statin-dose");
                if (doseSelect) {
                  doseSelect.disabled = this.value === "none";
                  doseSelect.innerHTML = "<option value=\"\" selected>Select dose</option>";
                  
                  if (this.value !== "none") {
                    // Define statin doses
                    const doses = {
                      atorvastatin: [
                        {value: "10", text: "10 mg", intensity: "moderate"},
                        {value: "20", text: "20 mg", intensity: "moderate"},
                        {value: "40", text: "40 mg", intensity: "high"},
                        {value: "80", text: "80 mg", intensity: "high"}
                      ],
                      rosuvastatin: [
                        {value: "5", text: "5 mg", intensity: "moderate"},
                        {value: "10", text: "10 mg", intensity: "moderate"},
                        {value: "20", text: "20 mg", intensity: "high"},
                        {value: "40", text: "40 mg", intensity: "high"}
                      ],
                      simvastatin: [
                        {value: "10", text: "10 mg", intensity: "low"},
                        {value: "20", text: "20 mg", intensity: "moderate"},
                        {value: "40", text: "40 mg", intensity: "moderate"}
                      ],
                      pravastatin: [
                        {value: "10", text: "10 mg", intensity: "low"},
                        {value: "20", text: "20 mg", intensity: "low"},
                        {value: "40", text: "40 mg", intensity: "moderate"},
                        {value: "80", text: "80 mg", intensity: "moderate"}
                      ],
                      lovastatin: [
                        {value: "10", text: "10 mg", intensity: "low"},
                        {value: "20", text: "20 mg", intensity: "low"},
                        {value: "40", text: "40 mg", intensity: "moderate"}
                      ],
                      fluvastatin: [
                        {value: "20", text: "20 mg", intensity: "low"},
                        {value: "40", text: "40 mg", intensity: "low"},
                        {value: "80", text: "80 mg", intensity: "moderate"}
                      ],
                      pitavastatin: [
                        {value: "1", text: "1 mg", intensity: "low"},
                        {value: "2", text: "2 mg", intensity: "moderate"},
                        {value: "4", text: "4 mg", intensity: "moderate"}
                      ]
                    };
                    
                    if (doses[this.value]) {
                      doses[this.value].forEach(dose => {
                        const option = document.createElement("option");
                        option.value = dose.value;
                        option.textContent = dose.text;
                        option.dataset.intensity = dose.intensity;
                        doseSelect.appendChild(option);
                      });
                    }
                  }
                }
              });
            }
            
            // Statin intolerance handler
            const intoleranceSelect = document.getElementById("med-statin-intolerance");
            if (intoleranceSelect) {
              intoleranceSelect.addEventListener("change", function() {
                const typeSelect = document.getElementById("med-intolerance-type");
                if (typeSelect) {
                  typeSelect.disabled = this.value === "no";
                }
              });
            }
            
            // PCSK9 checkbox handler
            const pcsk9Checkbox = document.getElementById("med-pcsk9");
            if (pcsk9Checkbox) {
              pcsk9Checkbox.addEventListener("change", function() {
                const pcsk9Details = document.getElementById("pcsk9-details");
                if (pcsk9Details) {
                  pcsk9Details.style.display = this.checked ? "block" : "none";
                }
              });
            }
            
            // Prevention category handler
            const preventionCategory = document.getElementById("prevention-category");
            if (preventionCategory) {
              preventionCategory.addEventListener("change", function() {
                const secondaryDetails = document.getElementById("secondary-details");
                if (secondaryDetails) {
                  secondaryDetails.disabled = this.value !== "secondary";
                }
              });
            }
          });
          EOL
      
      - name: Copy CSS file
        run: |
          if [ -f "styles.css.txt" ]; then
            echo "Copying styles.css.txt to combined/styles.css"
            cat styles.css.txt > combined/styles.css
          fi
      
      - name: Create simplified index.html
        run: |
          echo "Creating index.html skeleton"
          cat > combined/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="description" content="CVD Risk Toolkit with Lp(a) Post-Test Modifier">
              <meta name="author" content="CVD Risk Toolkit Team">
              <title>CVD Risk Toolkit with Lp(a) Post-Test Modifier</title>
              <link rel="preconnect" href="https://fonts.googleapis.com">
              <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
              <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
              <link rel="stylesheet" href="styles.css">
          </head>
          <body>
          EOL
          
          # Try to extract body content from index.txt
          if [ -f "index.txt" ]; then
            echo "Extracting body content from index.txt"
            sed -n '/<body>/,/<\/body>/p' index.txt | sed '1d;$d' >> combined/index.html
          fi
          
          # Close the HTML
          cat >> combined/index.html << 'EOL'
              <script src="combined.js"></script>
          </body>
          </html>
          EOL
      
      - name: List files in combined directory
        run: |
          echo "Files in combined directory:"
          ls -la combined
      
      # Push combined files to a new branch with proper permissions
      - name: Push combined files to a new branch
        run: |
          echo "Creating branch with combined files"
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git checkout -b combined-files
          git add combined/
          git commit -m "Add combined files" || echo "No changes to commit"
          git push -f origin combined-files || echo "Failed to push branch"
          
      - name: Upload artifacts to repository
        run: |
          echo "Creating combined files in main branch"
          git checkout main
          mkdir -p final
          cp combined/* final/
          git add final/
          git commit -m "Add final combined files to main branch" || echo "No changes to commit"
          git push origin main || echo "Failed to push to main"
